### ISSUE TITLE
Not getting properly formatted in the browser

### ISSUE THREAD

**Issue by tejas-kr** [knhash/jekyllBear#9]
I've encountered a rather peculiar issue. 

The site is properly formatted in my incognito browser but not in my main browser. 

![image](https://github.com/user-attachments/assets/dbf90f04-02bf-428d-8a32-68059d6306a2)
![image](https://github.com/user-attachments/assets/475fe7f6-c500-4439-b052-fa30afaa97ac)

I've had a similar issue with one another theme (https://github.com/riggraz/no-style-please/issues/85)
My current github page is hosted with this theme. (tejas-kr.github.io)

Kindly revert if you have any clue.

**Comment by knhash** [comment]
Hey.

All I can think of is there some css cached in your browser that is messing up the formatting, some override perhaps.

If it is working in incognito then it should also work on the hosted version of the website.

Cheers.

[[Shashank](https://knhash.in)]

**Comment by tejas-kr** [comment]
It's working in Arc and Firefox. The issue is with Chromium based browsers on windows. 
![image](https://github.com/user-attachments/assets/8c33f643-039f-4494-af81-c71dbc026c07)
